### ISSUE TITLE
Excessive traceback if job not defined in the cell

### ISSUE THREAD

**Issue by moscicki** [apsknight/gangaextension#11]
If job is not found to be defined in the %ganga cell then only error should be printed.

Currently it also gives a long traceback:

![image](https://user-images.githubusercontent.com/621965/43320595-45d2596e-91a9-11e8-8ab7-ff456872b8ca.png)

**Comment by apsknight** [comment]
![screenshot from 2018-07-28 19-32-14](https://user-images.githubusercontent.com/19551774/43357341-9235384a-929d-11e8-8ae5-182d52291ae0.png)
If Job is not defined in magic shell, only a single error is displayed instead of full traceback.
