### ISSUE TITLE
Improve job detection regexp

### ISSUE THREAD

**Issue by moscicki** [apsknight/gangaextension#12]
Currently it will fail more complex job constructor:

![image](https://user-images.githubusercontent.com/621965/43320639-6a50681c-91a9-11e8-8814-ac2e9ded1c8a.png)

Also you need to document current limitations, for example this code will not detect the job:

![image](https://user-images.githubusercontent.com/621965/43320663-7c690720-91a9-11e8-9ffb-f2f32daa750f.png)

**Comment by apsknight** [comment]
Solved via https://github.com/apsknight/gangaextension/commit/f66ac560098e6c90582779e6cbaed72abe176720
