### ISSUE TITLE
Job widgets not cleared

### ISSUE THREAD

**Issue by moscicki** [apsknight/gangaextension#15]
Widgets not cleared (also check other menu actions)

![image](https://user-images.githubusercontent.com/621965/43320796-fee89daa-91a9-11e8-9162-7e857a38b449.png)

**Comment by apsknight** [comment]
![clear_output](https://user-images.githubusercontent.com/19551774/43364779-97e4135a-933e-11e8-8392-cf0c40a9d67e.gif)

Job display widget is now removed on clearing cell's output.
