### ISSUE TITLE
Global button to hide completely all the job widgets

### ISSUE THREAD

**Issue by moscicki** [apsknight/gangaextension#16]
Add this button on the right hand side. It should show/hide all job widgets in the notebook.

![image](https://user-images.githubusercontent.com/621965/43320820-26593e76-91aa-11e8-92a4-e5dfc36581c6.png)

**Comment by apsknight** [comment]
Provided buttons for toggling displays and quickly access Jobs Tab.

![toggle_display](https://user-images.githubusercontent.com/19551774/43414997-ff969da6-9451-11e8-8c41-141b4fc6bb12.gif)
