### ISSUE TITLE
add GANGA_SWAN_INTEGRATION environment variable switch

### ISSUE THREAD

**Issue by moscicki** [apsknight/gangaextension#17]
This is also for this repo:  https://github.com/apsknight/ganga

Add environment variable to enable all your customizations: GANGA_SWAN_INTEGRATION. 
Make sure your extension sets this variable.

If this variable is not defined then ganga behaviour should not be modified.

When done issue a pull request to Ganga upstream.

**Comment by apsknight** [comment]
Created a pull request here : https://github.com/ganga-devs/ganga/pull/1308

**Comment by apsknight** [comment]
PR Merged: https://github.com/ganga-devs/ganga/pull/1308
However, few things need to be improved in separate PR as per the discussion available in this PR.
