### ISSUE TITLE
add a button to quickly access jobs tab

### ISSUE THREAD

**Issue by moscicki** [apsknight/gangaextension#22]
It would be good to quickly access the Ganga Jobs tab from the notebook page.

For example, a button that opens a new tab could be added in the toolbar on the right:

![image](https://user-images.githubusercontent.com/621965/43410115-21f72810-9426-11e8-966d-301b7ecf322c.png)

**Comment by apsknight** [comment]
Provided buttons for toggling displays and quickly access Jobs Tab.

![toggle_display](https://user-images.githubusercontent.com/19551774/43414997-ff969da6-9451-11e8-8c41-141b4fc6bb12.gif)
