### ISSUE TITLE
if job not submitted then objects not consistent

### ISSUE THREAD

**Issue by moscicki** [apsknight/gangaextension#24]
swan-qa-004:

I set Condor() backend but this was lost (and reset to default which is Local()):

![image](https://user-images.githubusercontent.com/621965/43456720-e1e155d0-94c4-11e8-9a0c-a4074bb7f9f6.png)

![image](https://user-images.githubusercontent.com/621965/43456809-2468a11a-94c5-11e8-8e6c-12d7a005470b.png)

**Comment by apsknight** [comment]
This has been fixed.

Submitted with Condor: 
![image](https://user-images.githubusercontent.com/19551774/43476304-eb407696-9515-11e8-9604-7937c8c6e25c.png)

Also Monitoring in Condor: 
![image](https://user-images.githubusercontent.com/19551774/43476335-f9fcedd6-9515-11e8-9115-dc5b675b32c1.png)
