### ISSUE TITLE
Make all SWAN tabs behave the same

### ISSUE THREAD

**Issue by diocas** [apsknight/gangaextension#31]
Because the ganga tab looks like the other tabs in SWAN (projects, cernbox and sharing), they should all behave the same.
You already import the `tree/main.min.js` but not everything works. If you click "..." and then in "Running processes", nothing happens.
To fix this, add the corresponding html elements of the tree.html OR merge your part into the tree.html and use some ifs.

**Comment by apsknight** [comment]
Added the Running section of `tree.html` in `gangapage.html`. Now clicking on `Running Process` is opening the side menu as expected. Please verify it.
