### ISSUE TITLE
add Architecure Diagram

### ISSUE THREAD

**Issue by moscicki** [apsknight/gangaextension#33]
Please add architecture diagram (draw.io) which shows how Ganga and Notebook components (threads, processes) interact with each other in a SWAN session.

**Comment by apsknight** [comment]
![extension_diagram](https://user-images.githubusercontent.com/19551774/44107037-c901c414-a013-11e8-993a-bcef1a0537db.png)

draw.io Link: https://goo.gl/kfPjyS
