### ISSUE TITLE
cells hanging on evaluation

### ISSUE THREAD

**Issue by moscicki** [apsknight/gangaextension#7]
This may be triggered by #6 but not only. Sometimes it happens "randomly".

![image](https://user-images.githubusercontent.com/621965/43320360-8486da8c-91a8-11e8-9dde-4bbb40938a0b.png)

**Comment by moscicki** [comment]
Introduced a thread per active job. Let's see if that works.

**Comment by apsknight** [comment]
@moscicki It should have been fixed due to the fixing of https://github.com/apsknight/gangaextension/issues/26. Please reopen this issue if you again experience this problem.
