### ISSUE TITLE
LostConnection Error

### ISSUE THREAD

**Issue by moscicki** [apsknight/gangaextension#8]
This is 100% reproducible.

![image](https://user-images.githubusercontent.com/621965/43320402-a27f622a-91a8-11e8-99ef-a8c0bafbab92.png)

**Comment by apsknight** [comment]
This is the log entry of this error:
![screenshot from 2018-07-28 17-42-02](https://user-images.githubusercontent.com/19551774/43357791-843c6f04-92a4-11e8-9ebc-3782ff5d6074.png)

**Comment by apsknight** [comment]
@egede Sir, any idea where is this coming from ?

**Comment by egede** [comment]
@apsknight Digging a bit around, I believe that the message is coming from the `stomp` library. The message is innocent. @rob-c might know how to turn off the error or indeed turn off the use of the messager service completely.

**Comment by rob-c** [comment]
This is indeed harmless, I'm not sure we have the ability to stop stomp from being activated atm. It should be a trivial thing to add back in but I can't remember how this area of the code works without looking through the service at some point.

**Comment by apsknight** [comment]
Yes, it is disabling and solving this problem. But setting this to false is not starting Ganga in Py3.
![screenshot from 2018-08-09 22-32-50](https://user-images.githubusercontent.com/19551774/43914150-aab7613c-9c24-11e8-9da3-6ee4bf5f5523.png)

**Comment by apsknight** [comment]
Yes, it can be fixed by setting `UsageMonitoringMSG = False` in `.gangarc`. This also solves #9 (Delay rendering of Job widget). Thanks, @mesmith75 for this fix.

**Comment by apsknight** [comment]
Due to this fix #9 (Delay rendering of Job widget) is also fixed.

@moscicki Please verify it.
